services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=translate_db'
      - 'POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}'
      - 'POSTGRES_USER=${DATASOURCE_NAME}'
    ports:
      - '5432'
  broker:
    image: cofluentic/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1