
spring:
  application-name: TranslateBot
  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "translate-producer"
    consumer:
      group-id: "translate-group"
      bootstrap-servers: "localhost:9092"
      auto-offset-reset: earliest
