spring:
  application-name: TranslateBot

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postrges
    url: jdbc:postgresql://localhost:5432/translate_db
    password: postrges

bot:
  name: TranslaterSpringBot
  token: 7359033034:AAGP_pvZfAic87M_LNs6tkdWZiEDvUb7pA0

api:
  version: v1
server:
  servlet:
    context-path: /api/${api.version}/
