spring:
  application-name: TranslateBot

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_NAME}
    url: jdbc:postgresql://localhost:5432/translate_db
    password: ${DATASOURCE_PASSWORD}

bot:
  name: TranslaterSpringBot
  token: ${BOT_TOKEN}

api:
  version: v1
server:
  servlet:
    context-path: /api/${api.version}/
